import { Routes } from '@angular/router';
import { HomeComponent } from '../Pages/home/home.component';
import { AboutComponent } from '../Pages/about/about.component';
import { MenuComponent } from '../Pages/menu/menu.component';
import { ContactComponent } from '../Pages/contact/contact.component';
import { ReserveNowComponent } from '../Pages/reserve-now/reserve-now.component';
import { FoodPackageComponent } from '../Pages/food-package/food-package.component';
import { CustomMenuComponent } from '../Pages/custom-menu/custom-menu.component';
import { PaymentComponent } from '../Pages/payment/payment.component';
import { GcashComponent } from '../Pages/gcash/gcash.component';
import { MayaComponent } from '../Pages/maya/maya.component';
import { ConfirmComponent } from '../Pages/confirm/confirm.component';
import { SignUpComponent } from '../Pages/sign-up/sign-up.component';
import { LoginComponent } from '../Pages/login/login.component';
import { FAQsComponents } from '../Pages/faqs/faqs.component';

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'about', component: AboutComponent },
    { path: 'menu', component: MenuComponent },
    { path: 'contact', component: ContactComponent },
    { path: 'reserve-now', component: ReserveNowComponent },
    { path: 'food-package', component: FoodPackageComponent },
    { path: 'custom-menu', component: CustomMenuComponent },
    { path: 'payment', component: PaymentComponent },
    { path: 'gcash', component: GcashComponent },
    { path: 'maya', component: MayaComponent },
    { path: 'confirm', component: ConfirmComponent },
    { path: 'sign-up', component: SignUpComponent },
    { path: 'login', component: LoginComponent },
    { path: 'faqs', component: FAQsComponents },
    { path: '**', redirectTo: '' }
];