import { Routes } from '@angular/router';
import { HomeComponent } from '../features/home/home.component';
import { AboutComponent } from '../features/about/about.component';
import { MenuComponent } from '../features/menu/menu.component';
import { ContactComponent } from '../features/contact/contact.component';
import { ReserveNowComponent } from '../features/reservation/components/reserve-now/reserve-now.component';
import { FoodPackageComponent } from '../features/reservation/components/food-package/food-package.component';
import { CustomMenuComponent } from '../features/reservation/components/custom-menu/custom-menu.component';
import { PaymentComponent } from '../features/payment/components/payment/payment.component';
import { GcashComponent } from '../features/payment/components/gcash/gcash.component';
import { MayaComponent } from '../features/payment/components/maya/maya.component';
import { ConfirmComponent } from '../features/reservation/components/confirm/confirm.component';
import { SignUpComponent } from '../features/auth/components/sign-up/sign-up.component';
import { LoginComponent } from '../features/auth/components/login/login.component';
import { FAQsComponents } from '../features/faqs/faqs.component';

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'about', component: AboutComponent },
    { path: 'menu', component: MenuComponent },
    { path: 'contact', component: ContactComponent },
    { path: 'reserve-now', component: ReserveNowComponent },
    { path: 'food-package', component: FoodPackageComponent },
    { path: 'custom-menu', component: CustomMenuComponent },
    { path: 'payment', component: PaymentComponent },
    { path: 'gcash', component: GcashComponent },
    { path: 'maya', component: MayaComponent },
    { path: 'confirm', component: ConfirmComponent },
    { path: 'sign-up', component: SignUpComponent },
    { path: 'login', component: LoginComponent },
    { path: 'faqs', component: FAQsComponents },
    { path: '**', redirectTo: '' }
];